export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER'; 
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const LOAD_USER = 'LOAD_USER';
export const CONNECTED_WALLET = 'CONNECTED_WALLET';
export const GET_BALANCE = 'GET_BALANCE';
export const CREATE_USER = 'CREATE_USER';
export const GET_USER = 'GET_USER';
export const GET_USERS = 'GET_USERS'; 
export const GET_USER_BY_USERNAME = 'GET_USER_BY_USERNAME';
export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR';
export const UPDATE_USER_COVER = 'UPDATE_USER_COVER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const GET_ASSET = 'GET_ASSET';
export const GET_ASSETS = 'GET_ASSETS';
export const GET_USER_ASSETS = 'GET_USER_ASSETS';
export const CREATE_ASSET = 'CREATE_ASSET';
export const UPDATE_ASSET = 'UPDATE_ASSET';
export const DELETE_ASSET = 'DELETE_USER';

// BlOCKCHAIN ACTIONS
export const GET_CONTRACT_ADDRESS = 'GET_CONTRACT_ADDRESS';
export const GET_ADDRESS = 'GET_ADDRESS';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const TOKEN_SUPPLY = 'TOKEN_SUPPLY';
export const UPDATE_WALLET_BALANCE = 'UPDATE_WALLET_BALANCE';
export const MINT_NFT = 'MINT_NFT';
export const UPDATE_ADMIN = 'UPDATE_ADMIN';
export const MINT = 'MINT';
export const START = 'START';
export const BUY_TOKENS = 'BUY_TOKENS';
export const BUY_XLN = 'BUY_XLN';
export const WITHDRAW_TOKENS = 'WITHDRAW_TOKENS';
export const WITHDRAW_DAI = 'WITHDRAW_DAI';
export const GET_LISTING_PRICE = 'GET_LISTING_PRICE';
export const MAKE_MARKET_ITEM = 'MAKE_MARKET_ITEM';
export const CREATE_MARKET_SALE = 'CREATE_MARKET_SALE';
export const FETCH_MARKET_TOKENS = 'FETCH_MARKET_TOKENS';
export const FETCH_MY_NFTS = 'FETCH_MY_NFTS';
export const FETCH_ITEMS_CREATED = 'FETCH_ITEMS_CREATED';


// ERRORS
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_ERROR = 'USER_ERROR';
export const CHAIN_ERROR = 'CHAIN_ERROR';