import React, { useReducer } from 'react';
import { createAsset } from './asset';

// TODO:  Call file aiAction

import axios from '../axios';
import {
   CREATE_ASSET,
   OPEN_CV,
   GENERATE_ART,
   AI_ERROR,
   ASSET_ERROR
} from './types';


export const generateArt = ({ id, assetId = "", blockchain, values: { model, prompt, size, numOfImg }}) => async dispatch => {

let res
let asset
let assetNum = assetId;
let assetIdCharLimit = assetId.split("").length;
let promptCharLimit = prompt.split("").length;

if( assetIdCharLimit == 0 ){
    const joinedPrompt = prompt.split(" ").join("").slice(0, 47 )
    const promptSlug = joinedPrompt.replace(/[^a-zA-Z0-9 ]/g, '').toLowerCase();

    try{
    asset = await axios.post(`/api/v1/assets/`, {
            assetType: 'AI',
            name: promptSlug,
            category: "ai, art, art generation, text prompt, prompt, artificial intelligence",
            description: "Text prompt generated by userId: #",
            price: 50,
            stock: 17 
          } );

    if( asset.data.success ){
        assetNum = asset.data.data.created
    }

    dispatch({
        type: CREATE_ASSET,
        payload: res.data
    })
    } catch(err){
    dispatch({ type: ASSET_ERROR, payload: err})
}
}

try {
    res = await axios.post(`/api/v1/assets/${assetNum}/ai/art`, { model, prompt, size, numOfImg });

        dispatch({
            type: GENERATE_ART,
            payload: res.data
        })
} catch(err){
    dispatch({ type: AI_ERROR, payload: err })
}
   
}

export const opencv = () => async dispatch => {
    try{
      console.log("Open cv action")
      const res = await axios.get(`/api/v1/ai/hands`);

      console.log('Action OpenCV  ----', res.data)

        dispatch({
            type: OPEN_CV,
            payload: res.data
        })
    } catch(err){
        dispatch({ type: API_ERROR, payload: err})
    }
}