/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Polygon.by - Art & Gamedev (https://sketchfab.com/polygonschool)
license: SKETCHFAB Editorial (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/lambo-aventador-e8a99a5d8900490aaa0c3a68ae78d639
title: Lambo Aventador
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Lambo({ ...props }) {
  return(
    <h4>Lambo</h4>
  );
  // const group = useRef()
  // const { nodes, materials } = useGLTF('./images/model/lambo-transformed.glb')
  // return (
  //   <group ref={group} {...props} dispose={null}>
  //     <group rotation={[-Math.PI / 2, 0, 0]}>
  //       <group rotation={[Math.PI / 2, 0, 0]}>
  //         <group position={[-0.14, 1.15, -0.66]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
  //           <mesh geometry={nodes['1_CAR_BODY_BODY_YELOU_0'].geometry} material={materials.BODY_YELOU} />
  //           <mesh geometry={nodes['1_CAR_BODY_BOBY_BLACK_0'].geometry} material={materials.BOBY_BLACK} />
  //           <mesh geometry={nodes['1_CAR_BODY_Material_#44_0'].geometry} material={materials.Material_44} />
  //           <mesh geometry={nodes['1_CAR_BODY_GLASS_0'].geometry} material={materials.GLASS} />
  //           <mesh geometry={nodes['1_CAR_BODY_LIGHTER_0'].geometry} material={materials.LIGHTER} />
  //           <mesh geometry={nodes['1_CAR_BODY_WIRE_0'].geometry} material={materials.WIRE} />
  //         </group>
  //         <group position={[-0.44, 0.36, 1.08]} rotation={[0, -Math.PI / 2, 0]}>
  //           <mesh geometry={nodes.wheel_arches_wheel_arches_0.geometry} material={materials.wheel_arches} />
  //         </group>
  //         <group position={[0.31, 0.87, -1.38]} rotation={[-Math.PI / 2, 0, 0]}>
  //           <mesh geometry={nodes.engine_BOBY_BLACK_0.geometry} material={materials.BOBY_BLACK} />
  //         </group>
  //         <group position={[0.16, 0.76, 1.29]} rotation={[-1.4, 0, -0.09]}>
  //           <mesh geometry={nodes.Box002_BOBY_BLACK_0.geometry} material={materials.BOBY_BLACK} />
  //         </group>
  //         <group position={[-0.63, 0.35, 1.08]} rotation={[-2.93, -Math.PI / 2, 0]} scale={[1.1, 1.1, 1.05]}>
  //           <group position={[0, 0.16, 0]}>
  //             <mesh geometry={nodes.wheel_disk_1_BOBY_BLACK_0.geometry} material={materials.BOBY_BLACK} />
  //           </group>
  //         </group>
  //         <group position={[-0.59, 0.63, 1.08]} rotation={[Math.PI, 0, -Math.PI]}>
  //           <group position={[0.01, 0, 0.13]}>
  //             <mesh geometry={nodes['TIRE_1_Material_#38_0'].geometry} material={materials.Material_38} />
  //           </group>
  //         </group>
  //         <group position={[-0.69, 0.36, -1.62]} rotation={[-2.93, -Math.PI / 2, 0]} scale={[1.16, 1.16, 1.05]}>
  //           <group position={[0, 0.16, 0]}>
  //             <mesh geometry={nodes.wheel_disk_2_BOBY_BLACK_0.geometry} material={materials.BOBY_BLACK} />
  //           </group>
  //         </group>
  //         <group position={[-0.64, 0.66, -1.62]} rotation={[Math.PI, 0, -Math.PI]} scale={[1, 1.05, 1.05]}>
  //           <group position={[0.01, 0, 0.13]}>
  //             <mesh geometry={nodes['TIRE_2_Material_#38_0'].geometry} material={materials.Material_38_0} />
  //           </group>
  //         </group>
  //       </group>
  //     </group>
  //   </group>
  //)
}

//useGLTF.preload('./images/model/lambo-transformed.glb')
