/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useEffect } from 'react'

export default function Model({ controls, ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/images/model/lola.glb')
  const { actions } = useAnimations(animations, group)
   console.log({ actions })
  const previousAction = usePrevious(controls);
  useEffect(() => {
    if(previousAction){ 
      actions[previousAction].fadeOut(0.3)
      actions[previousAction].stop()
    }
    actions[controls].play();
    previousAction && actions[previousAction].fadeIn(0.3)
    console.log('Loop', actions[controls]._clip.duration * 1000 )
    setTimeout(() => actions[controls].stop(), actions[controls]._clip.duration * 1000 );
  }, [ controls ])

  return (
    <group ref={group} {  ...props } dispose={null}>
      <group name="Scene">
        <group name="Camera" position={[7.36, 4.96, 6.93]} rotation={[1.24, 0.33, -0.76]} />
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Lola" geometry={nodes.Lola.geometry} material={materials.phong1} skeleton={nodes.Lola.skeleton} />
        </group>
        <group name="Armature001" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="mixamorigHips_1" position={[3.15, -1.72, -103.04]} rotation={[-1.4, -1.08, 0.18]}>
            <group name="mixamorigSpine_1" position={[0, 10.87, -0.83]} rotation={[0.19, 0, -0.07]}>
              <group name="mixamorigSpine1_1" position={[0, 12.72, 0]} rotation={[0.1, 0.01, -0.05]}>
                <group name="mixamorigSpine2_1" position={[0, 14.54, 0]} rotation={[0.18, 0.01, -0.05]}>
                  <group name="mixamorigNeck_1" position={[0, 16.31, -1.24]} rotation={[-0.06, 0.03, 0.07]}>
                    <group name="mixamorigHead_1" position={[0, 11.18, 5.13]} rotation={[-0.35, 0.96, 0.04]}>
                      <group name="mixamorigHeadTop_End_1" position={[0, 19.36, 1.98]} />
                      <group name="mixamorigLeftEye_1" position={[3, 7.22, 8]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
                      <group name="mixamorigRightEye_1" position={[-3.04, 7.22, 8]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
                    </group>
                  </group>
                  <group name="mixamorigLeftShoulder_1" position={[5.91, 14.35, -1.22]} rotation={[1.63, -0.38, -1.51]}>
                    <group name="mixamorigLeftArm_1" position={[0, 12.44, 0]} rotation={[0.66, -0.8, 0.11]}>
                      <group name="mixamorigLeftForeArm_1" position={[0, 27.89, 0]} rotation={[-0.01, 0, 0.82]}>
                        <group name="mixamorigLeftHand_1" position={[0, 28.33, 0]} rotation={[-0.01, -0.18, 0]}>
                          <group name="mixamorigLeftHandThumb1_1" position={[-2.44, 3.25, 0.95]} rotation={[0.58, 0.98, 0.36]}>
                            <group name="mixamorigLeftHandThumb2_1" position={[0, 3.34, 0]} rotation={[-0.1, 0.02, -0.54]}>
                              <group name="mixamorigLeftHandThumb3_1" position={[0, 3.75, 0]} rotation={[-0.22, 0.07, -0.78]}>
                                <group name="mixamorigLeftHandThumb4_1" position={[0, 2.99, 0]} />
                              </group>
                            </group>
                          </group>
                          <group name="mixamorigLeftHandIndex1_1" position={[-2.44, 9.64, 0.29]} rotation={[1.07, 0.01, -0.13]}>
                            <group name="mixamorigLeftHandIndex2_1" position={[0, 3.11, 0]} rotation={[1.55, -0.13, -0.15]}>
                              <group name="mixamorigLeftHandIndex3_1" position={[0, 2.85, 0]} rotation={[0.72, -0.07, -0.13]}>
                                <group name="mixamorigLeftHandIndex4_1" position={[0, 2.38, 0]} />
                              </group>
                            </group>
                          </group>
                          <group name="mixamorigLeftHandMiddle1_1" position={[0, 9.9, 0]} rotation={[1.1, -0.09, 0]}>
                            <group name="mixamorigLeftHandMiddle2_1" position={[0, 3.76, 0]} rotation={[1.49, -0.16, -0.16]}>
                              <group name="mixamorigLeftHandMiddle3_1" position={[0, 3.62, 0]} rotation={[0.65, -0.02, -0.09]}>
                                <group name="mixamorigLeftHandMiddle4_1" position={[0, 3.11, 0]} />
                              </group>
                            </group>
                          </group>
                          <group name="mixamorigLeftHandRing1_1" position={[2.66, 8.99, 0.18]} rotation={[1.08, -0.23, 0.05]}>
                            <group name="mixamorigLeftHandRing2_1" position={[0, 3.49, 0]} rotation={[1.15, -0.09, -0.2]}>
                              <group name="mixamorigLeftHandRing3_1" position={[0, 3.51, 0]} rotation={[1.21, -0.12, -0.17]}>
                                <group name="mixamorigLeftHandRing4_1" position={[0, 3.13, 0]} />
                              </group>
                            </group>
                          </group>
                          <group name="mixamorigLeftHandPinky1_1" position={[4.37, 7.8, 0.19]} rotation={[0.96, -0.39, 0.1]}>
                            <group name="mixamorigLeftHandPinky2_1" position={[0, 3.22, 0]} rotation={[1.46, -0.13, -0.17]}>
                              <group name="mixamorigLeftHandPinky3_1" position={[0, 2.62, 0]} rotation={[1.02, -0.09, -0.15]}>
                                <group name="mixamorigLeftHandPinky4_1" position={[0, 2.22, 0]} />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="mixamorigRightShoulder_1" position={[-5.94, 14.35, -1.22]} rotation={[1.62, 0.32, 1.43]}>
                    <group name="mixamorigRightArm_1" position={[0, 12.44, 0]} rotation={[0.75, 0.05, 0.21]}>
                      <group name="mixamorigRightForeArm_1" position={[0, 27.89, 0]} rotation={[0.26, 0.2, -0.71]}>
                        <group name="mixamorigRightHand_1" position={[0, 28.33, 0]} rotation={[-0.35, 0.51, -0.01]}>
                          <group name="mixamorigRightHandThumb1_1" position={[2.44, 3.25, 0.95]} rotation={[0.6, -0.15, -0.41]}>
                            <group name="mixamorigRightHandThumb2_1" position={[0, 3.34, 0]} rotation={[-0.1, 0.03, 0.44]}>
                              <group name="mixamorigRightHandThumb3_1" position={[0, 3.75, 0]} rotation={[0.03, -0.02, -0.27]}>
                                <group name="mixamorigRightHandThumb4_1" position={[0, 2.99, 0]} />
                              </group>
                            </group>
                          </group>
                          <group name="mixamorigRightHandIndex1_1" position={[2.44, 9.64, 0.29]} rotation={[0.01, 0, -0.01]}>
                            <group name="mixamorigRightHandIndex2_1" position={[0, 3.11, 0]} rotation={[0.09, 0, 0]}>
                              <group name="mixamorigRightHandIndex3_1" position={[0, 2.85, 0]} rotation={[-0.05, 0, 0.03]}>
                                <group name="mixamorigRightHandIndex4_1" position={[0, 2.38, 0]} />
                              </group>
                            </group>
                          </group>
                          <group name="mixamorigRightHandMiddle1_1" position={[0, 9.9, 0]} rotation={[0.04, 0, 0.1]}>
                            <group name="mixamorigRightHandMiddle2_1" position={[0, 3.76, 0]} rotation={[0.42, 0.01, 0.08]}>
                              <group name="mixamorigRightHandMiddle3_1" position={[0, 3.62, 0]} rotation={[-0.1, 0, -0.03]}>
                                <group name="mixamorigRightHandMiddle4_1" position={[0, 3.11, 0]} />
                              </group>
                            </group>
                          </group>
                          <group name="mixamorigRightHandRing1_1" position={[-2.66, 8.99, 0.18]} rotation={[0.07, -0.01, 0.21]}>
                            <group name="mixamorigRightHandRing2_1" position={[0, 3.49, 0]} rotation={[0.47, 0, 0.07]}>
                              <group name="mixamorigRightHandRing3_1" position={[0, 3.51, 0]} rotation={[0.34, 0, 0.07]}>
                                <group name="mixamorigRightHandRing4_1" position={[0, 3.13, 0]} />
                              </group>
                            </group>
                          </group>
                          <group name="mixamorigRightHandPinky1_1" position={[-4.37, 7.8, 0.19]} rotation={[0.19, 0.03, 0.34]}>
                            <group name="mixamorigRightHandPinky2_1" position={[0, 3.22, 0]} rotation={[0.33, -0.04, 0.05]}>
                              <group name="mixamorigRightHandPinky3_1" position={[0, 2.62, 0]} rotation={[0.5, -0.06, 0.13]}>
                                <group name="mixamorigRightHandPinky4_1" position={[0, 2.22, 0]} />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group name="mixamorigLeftUpLeg_1" position={[12.5, -6.04, 1.64]} rotation={[-0.6, 0.22, -2.74]}>
              <group name="mixamorigLeftLeg_1" position={[0, 51.64, 0]} rotation={[-0.7, 0.12, 0.03]}>
                <group name="mixamorigLeftFoot_1" position={[0, 44.3, 0]} rotation={[1.12, -0.22, 0.01]}>
                  <group name="mixamorigLeftToeBase_1" position={[0, 20.53, 0]} rotation={[0.66, -0.11, -0.01]}>
                    <group name="mixamorigLeftToe_End_1" position={[0, 8.19, 0]} />
                  </group>
                </group>
              </group>
            </group>
            <group name="mixamorigRightUpLeg_1" position={[-12.5, -6.04, 1.64]} rotation={[-0.51, -0.36, 2.59]}>
              <group name="mixamorigRightLeg_1" position={[0, 51.64, 0]} rotation={[-0.68, -0.06, -0.08]}>
                <group name="mixamorigRightFoot_1" position={[0, 44.3, 0]} rotation={[1.2, 0.33, 0.04]}>
                  <group name="mixamorigRightToeBase_1" position={[0, 20.53, 0]} rotation={[0.63, 0.1, 0.01]}>
                    <group name="mixamorigRightToe_End_1" position={[0, 8.19, 0]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

function usePrevious(value){
  const ref = useRef();

  useEffect(() => {
    console.log('Default', value)
     ref.current = value;
  }, [value])

  return ref.current
}

useGLTF.preload('/images/model/lola.glb')